# Generated by Django 4.0.1 on 2023-04-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices_in_complete_thought',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='dc_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='question',
            name='relevant_sentences',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='knowledge_component',
            field=models.CharField(max_length=255),
        ),
    ]
