# Generated by Django 4.0.1 on 2023-04-23 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_question_choices_in_complete_thought_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='submission_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
