# Generated by Django 4.0.1 on 2023-05-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_useranswer_submission_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(default=''),
        ),
    ]
