# Generated by Django 4.0.1 on 2023-06-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_userprofile_diagnostic_test_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='model',
            field=models.CharField(default='', max_length=50),
        ),
    ]
