# Generated by Django 4.0.1 on 2023-06-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_userprofile_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='history',
        ),
    ]
