# Generated by Django 4.0.1 on 2023-06-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_alter_userprofile_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
